/**********************************************************************
** Copyright (C) 2002 Michael 'Mickey' Lauer.  All rights reserved.
**
** This file is part of Opie Environment.
**
** This file may be distributed and/or modified under the terms of the
** GNU General Public License version 2 as published by the Free Software
** Foundation and appearing in the file LICENSE.GPL included in the
** packaging of this file.
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
***********************************************************************/

#include "wellenreiterbase.h"

#include <qheader.h>
#include <qlabel.h>
#include <qlistview.h>
#include <qmultilineedit.h>
#include <qpushbutton.h>
#include <opie/otabwidget.h>
#include <qlayout.h>
#include <qvariant.h>
#include <qtooltip.h>
#include <qwhatsthis.h>
#include <qimage.h>
#include <qpixmap.h>

static const char* const image0_data[] = { 
"150 105 949 2",
"g0 c #000000",
"g3 c #000008",
"g1 c #000400",
"i5 c #000408",
"g2 c #080000",
"hD c #080008",
"hB c #080400",
"g4 c #080408",
"gA c #080808",
"gz c #080c08",
"kk c #080c10",
"ij c #100000",
"kQ c #100408",
"hA c #100c10",
"gB c #101010",
"lD c #101410",
"ie c #180000",
"iC c #180400",
"gC c #181418",
"lb c #181810",
"gy c #181818",
"kM c #181c18",
"j2 c #182018",
"lB c #200000",
"jx c #200408",
"jv c #201820",
"hY c #201c20",
"iz c #202020",
"ho c #202420",
"lR c #290000",
"lS c #290008",
"mi c #292429",
"gx c #292829",
"iB c #292c29",
"hC c #312c29",
"im c #312c31",
"hj c #313031",
"mR c #313431",
"kP c #390000",
"ku c #393439",
"hi c #393831",
"kt c #393839",
"kN c #393c39",
"ii c #410000",
"mE c #413c41",
"gw c #414041",
"hX c #414441",
"lf c #41444a",
"kD c #4a0000",
"g5 c #4a444a",
"iK c #4a484a",
"mS c #4a4c4a",
"jw c #520008",
"hn c #524c4a",
"hp c #524c52",
"hT c #525052",
"lx c #52505a",
"hG c #525552",
"jh c #5a555a",
"iL c #5a595a",
"gv c #5a5d5a",
"iJ c #620000",
"mq c #625d62",
"hU c #626162",
"l8 c #626562",
"ig c #6a0000",
"jk c #6a0400",
"ik c #6a246a",
"hH c #6a286a",
"jM c #6a656a",
"hm c #6a696a",
"mj c #6a6d6a",
"i1 c #730008",
"kr c #732c73",
"mm c #733073",
"le c #736d73",
"gY c #737173",
"mh c #737573",
"lA c #7b0000",
"i6 c #7b347b",
"hE c #7b387b",
"lu c #7b6d10",
"kh c #7b797b",
"kj c #7b7d7b",
"lc c #830000",
"kW c #830400",
"mA c #833c83",
"gZ c #834083",
"lF c #836900",
"bd c #836d00",
"fO c #836d08",
"lv c #836d10",
"c8 c #837100",
"cq c #837108",
"fB c #837110",
"lG c #837118",
"f7 c #837120",
"iQ c #837129",
"hv c #837518",
"d1 c #837520",
"jy c #837529",
"gm c #837531",
"ha c #837539",
"fp c #837931",
"kv c #837939",
"mu c #837d83",
"iy c #83817b",
"gD c #838183",
"kF c #838583",
"iD c #8b0000",
"lT c #8b448b",
"mG c #8b488b",
"mM c #8b4c8b",
"bb c #8b6d00",
"lE c #8b6d08",
"aT c #8b7100",
"cH c #8b7108",
"ft c #8b7110",
"#H c #8b7500",
"af c #8b7508",
"az c #8b7510",
"#K c #8b7518",
"ds c #8b7520",
"lX c #8b7529",
"fe c #8b7900",
"#q c #8b7908",
"jO c #8b7910",
"bg c #8b7918",
"c. c #8b7920",
"fL c #8b7929",
"h4 c #8b7939",
"i9 c #8b7941",
"jE c #8b7d20",
"i. c #8b7d29",
"cb c #8b7d31",
"ex c #8b7d39",
"eO c #8b7d41",
"e5 c #8b7d4a",
"iu c #8b8129",
"hS c #8b8131",
"eQ c #8b8139",
"ls c #8b8141",
"gM c #8b814a",
"dN c #8b8152",
"k# c #8b855a",
"i0 c #8b858b",
"id c #8b898b",
"hh c #8b8d8b",
"hk c #8b8d94",
"if c #940400",
"mw c #944c94",
"il c #945094",
"eX c #947500",
"eV c #947508",
"aE c #947510",
"mF c #947594",
"i# c #947900",
"e7 c #947908",
"bR c #947910",
"bu c #947918",
"c6 c #947920",
"jf c #947d08",
"## c #947d10",
"b2 c #947d18",
"a5 c #947d20",
"jb c #948110",
"aG c #948118",
".Z c #948120",
"#2 c #948129",
"bw c #948131",
"#8 c #948139",
"fI c #948141",
"kc c #948152",
"gf c #948520",
"bP c #948529",
"c2 c #948531",
"d4 c #948539",
"ek c #948541",
"gg c #94854a",
"cd c #948552",
"dR c #948939",
"dp c #948941",
"by c #94894a",
"fF c #948952",
"ky c #94895a",
"fK c #948962",
"h. c #94896a",
"ff c #948d52",
"cR c #948d5a",
"eA c #948d6a",
"me c #948d94",
"lL c #94916a",
"hu c #949173",
"hw c #94917b",
"hI c #949194",
"ms c #949594",
"mU c #9c759c",
"mn c #9c799c",
"j9 c #9c7d10",
"kR c #9c7d9c",
"ic c #9c7da4",
"e4 c #9c8118",
"dH c #9c8120",
"fc c #9c8129",
"e# c #9c8518",
"dj c #9c8520",
".O c #9c8529",
"#p c #9c8531",
"#T c #9c8539",
"fD c #9c854a",
"e0 c #9c8920",
"cC c #9c8929",
"#t c #9c8931",
".G c #9c8939",
"dF c #9c8941",
"#Z c #9c894a",
"jC c #9c8952",
"cA c #9c8d31",
"d7 c #9c8d39",
"#V c #9c8d41",
"ao c #9c8d4a",
"fT c #9c8d52",
"fG c #9c8d62",
"#x c #9c914a",
"df c #9c9152",
"fy c #9c9162",
"da c #9c916a",
"du c #9c9173",
"gX c #9c9573",
"lJ c #9c957b",
"ef c #9c9583",
"jI c #9c959c",
"m# c #9c9983",
"jL c #9c999c",
"jP c #9c9d8b",
"mr c #9c9d9c",
"ji c #a40000",
"ld c #a40408",
"mL c #a47da4",
"kS c #a481a4",
"cS c #a48929",
"bI c #a48931",
"ew c #a48d29",
"ai c #a48d31",
"gr c #a48d39",
"l# c #a49131",
"gV c #a49139",
"eT c #a49141",
".x c #a4914a",
"#. c #a49152",
"dg c #a4915a",
"l. c #a49539",
"#9 c #a49541",
"ep c #a4954a",
"a3 c #a49552",
"#i c #a4955a",
"lp c #a4956a",
"bf c #a49952",
"aR c #a4995a",
".8 c #a49962",
"gh c #a4997b",
"bq c #a49d5a",
"cB c #a49d6a",
"fv c #a49d73",
"ax c #a49d7b",
"bl c #a49d83",
"eb c #a49d8b",
"jq c #a49d94",
"eM c #a4a17b",
"fi c #a4a183",
"d2 c #a4a18b",
"jY c #a4a194",
"mb c #a4a19c",
"mO c #a4a1a4",
"dI c #a4a58b",
"hK c #a4a59c",
"mp c #a4a5a4",
"kB c #a4a5ac",
"ks c #ac0400",
"hz c #ac85ac",
"ml c #ac89ac",
"iV c #ac9139",
"ez c #ac9541",
"cr c #ac954a",
"j8 c #ac994a",
"#G c #ac9952",
".r c #ac995a",
"fQ c #ac996a",
"ck c #ac9d4a",
"g8 c #ac9d52",
"eW c #ac9d5a",
"bB c #ac9d62",
"eZ c #ac9d6a",
"#D c #aca162",
".U c #aca16a",
".9 c #aca173",
"ei c #aca17b",
"jV c #aca194",
"dC c #aca56a",
"ae c #aca573",
"e. c #aca583",
"i8 c #aca58b",
"fm c #aca594",
"f2 c #aca59c",
"my c #aca5ac",
"jU c #acaa8b",
"jg c #acaa94",
"dd c #acaa9c",
"l2 c #acaaa4",
"jN c #acaaac",
"kx c #acaea4",
"lU c #acaeac",
"iI c #b40000",
"ih c #b40400",
"ki c #b46db4",
"md c #b48db4",
"mB c #b491b4",
"eD c #b4a152",
"cV c #b4a15a",
"iv c #b4a162",
"b0 c #b4a16a",
".l c #b4a173",
"dT c #b4a17b",
"iO c #b4a55a",
"dU c #b4a562",
"eE c #b4a56a",
".V c #b4a573",
"at c #b4a57b",
"jG c #b4aa62",
"d# c #b4aa6a",
"dm c #b4aa73",
".S c #b4aa7b",
".J c #b4aa83",
"cY c #b4aa8b",
"bA c #b4ae7b",
"#k c #b4ae8b",
"jA c #b4ae94",
"cl c #b4ae9c",
"fY c #b4aea4",
"lI c #b4aeac",
"mD c #b4aeb4",
"dB c #b4b294",
"eC c #b4b29c",
"dP c #b4b2a4",
"gT c #b4b2ac",
"gt c #b4b2b4",
"bZ c #b4b6ac",
"l5 c #b4b6b4",
"h1 c #b4babd",
"j3 c #bd0408",
"mJ c #bd75bd",
"jl c #bd79bd",
"mx c #bd95bd",
"mg c #bd99bd",
"mz c #bd9dbd",
"db c #bdaa62",
"go c #bdaa6a",
"bK c #bdae6a",
"is c #bdae73",
"cL c #bdae7b",
"ap c #bdae83",
"f3 c #bdae8b",
"gN c #bdb273",
"aN c #bdb27b",
".h c #bdb283",
".C c #bdb294",
"dX c #bdb2a4",
"kl c #bdb67b",
"aa c #bdb68b",
".Y c #bdb694",
"c4 c #bdb69c",
"gb c #bdb6a4",
"bW c #bdb6ac",
"gs c #bdb6b4",
"in c #bdb6bd",
"lo c #bdba9c",
"al c #bdbaa4",
"aY c #bdbaac",
"fZ c #bdbab4",
"gP c #bdbabd",
"eR c #bdbebd",
"cU c #bdbec5",
"fl c #bdc2bd",
"ib c #bdc6c5",
"lz c #c50000",
"kC c #c50400",
"lw c #c56d08",
"dc c #c57108",
"lt c #c57118",
"mH c #c57dc5",
"gu c #c581c5",
"hV c #c585cd",
"iT c #c58d00",
"jc c #c58d08",
"lQ c #c59100",
"k. c #c59531",
"j6 c #c59dc5",
"mN c #c5a1c5",
"k4 c #c5b673",
"jo c #c5b67b",
"dM c #c5b683",
"lV c #c5ba7b",
"dO c #c5ba83",
"#d c #c5ba8b",
"#3 c #c5ba94",
"ab c #c5ba9c",
"#F c #c5be9c",
"cy c #c5beac",
"fj c #c5beb4",
".5 c #c5c29c",
".e c #c5c2a4",
"cg c #c5c2ac",
"dx c #c5c2bd",
"f1 c #c5c2c5",
"eG c #c5c6bd",
"hc c #c5c6c5",
"cX c #c5c6cd",
"kT c #c5cacd",
"jj c #cd0000",
"jJ c #cd0008",
"jK c #cd0400",
"j5 c #cd0408",
"cx c #cd6d00",
"b1 c #cd7100",
"aX c #cd7108",
"ht c #cd7110",
"kn c #cd7129",
"ed c #cd7500",
"as c #cd7508",
"kG c #cd7510",
"bi c #cd7518",
"gp c #cd7910",
"kd c #cd7931",
"h0 c #cd7d39",
"lC c #cd89cd",
"br c #cd8d00",
"bT c #cd9100",
"bU c #cd9108",
"cT c #cd9118",
"jW c #cd9120",
"bt c #cd9500",
"g9 c #cd9508",
"fA c #cd9510",
"gQ c #cd9518",
"ip c #cd9520",
"lW c #cd956a",
"bp c #cd9908",
"e2 c #cd9920",
"cW c #cd9929",
"lP c #cd9931",
"lY c #cd9939",
"lO c #cd9d7b",
"lZ c #cd9d8b",
"g6 c #cda5cd",
"j1 c #cdaacd",
"kL c #cdaecd",
"k2 c #cdbe8b",
"fr c #cdbe9c",
"ec c #cdc294",
"cP c #cdc29c",
"aW c #cdc2a4",
"eU c #cdc2ac",
"lk c #cdc694",
"h7 c #cdc69c",
"ct c #cdc6a4",
"#Q c #cdc6ac",
".p c #cdc6b4",
"b6 c #cdc6bd",
".W c #cdcaac",
"ln c #cdcab4",
"eK c #cdcabd",
"cD c #cdcacd",
"mc c #cdcad5",
"cN c #cdcec5",
"bF c #cdcecd",
"eP c #cdced5",
"iF c #d50000",
"i3 c #d50400",
"fo c #d57100",
"c5 c #d57500",
"f5 c #d57508",
"cZ c #d57510",
"gI c #d57900",
"b5 c #d57908",
"b3 c #d57910",
"#4 c #d57918",
"c9 c #d57920",
"ke c #d57d08",
"aw c #d57d10",
"bC c #d57d18",
"be c #d57d20",
"fk c #d57d31",
"fV c #d58120",
"aU c #d58129",
"fh c #d58131",
"hZ c #d58139",
"hg c #d58141",
"jD c #d58539",
"bL c #d58541",
"lH c #d5854a",
"lr c #d58552",
"gO c #d5855a",
"cE c #d58952",
"iq c #d5895a",
"fq c #d58962",
"jH c #d589cd",
"mW c #d58dd5",
"cQ c #d59100",
"dk c #d59108",
"hl c #d591d5",
"aJ c #d59500",
"a4 c #d59508",
"eu c #d59510",
"cM c #d59518",
"mo c #d595d5",
"bx c #d59900",
"#A c #d59908",
"ak c #d59910",
"bY c #d59918",
"er c #d59d08",
"#h c #d59d10",
"cG c #d59d18",
"bn c #d59d20",
"#X c #d59d31",
"dZ c #d59d6a",
"kq c #d59d83",
"dh c #d5a118",
"#B c #d5a120",
"di c #d5a129",
"eS c #d5a139",
"a8 c #d5a17b",
"e8 c #d5a18b",
"aL c #d5a583",
"dr c #d5a58b",
"hM c #d5a59c",
"fz c #d5aa83",
"kK c #d5aa8b",
"jZ c #d5aa94",
"lN c #d5aa9c",
"jd c #d5aaa4",
"kw c #d5aaac",
"jt c #d5ae9c",
"mv c #d5aed5",
"hF c #d5b2d5",
"a7 c #d5c69c",
"js c #d5ca9c",
"fR c #d5caa4",
"d5 c #d5caac",
"bN c #d5cab4",
"h2 c #d5cea4",
"a1 c #d5ceac",
"aO c #d5cebd",
"c1 c #d5cec5",
"jm c #d5cecd",
"mT c #d5ced5",
"c0 c #d5d2b4",
"an c #d5d2bd",
"gG c #d5d2c5",
"aB c #d5d2cd",
"bj c #d5d2d5",
"l4 c #d5d2de",
"b# c #d5d6cd",
"#N c #d5d6d5",
"hs c #d5d6de",
"kp c #d5d6ff",
"f# c #d5dade",
"iG c #de0000",
"ly c #de0008",
"i4 c #de0400",
"he c #de7d10",
"cv c #de8120",
"aQ c #de8129",
"dA c #de8520",
"aq c #de8529",
"au c #de8531",
"cu c #de8539",
"gL c #de8920",
"cc c #de8929",
"aP c #de8931",
"#M c #de8941",
"hr c #de8962",
"aS c #de8d31",
"fg c #de8d41",
"#I c #de8d4a",
"hf c #de8d52",
"bJ c #de8d5a",
"iR c #de8d62",
"fX c #de8d6a",
"ea c #de9162",
"ko c #de9173",
"kb c #de9573",
"iA c #de95de",
"fN c #de9908",
"kE c #de99de",
"mt c #de9dde",
"iU c #dea110",
"hx c #dea118",
".7 c #dea120",
"hL c #dea518",
"fJ c #dea520",
".T c #dea529",
"bv c #dea56a",
"dl c #dea573",
"do c #dea57b",
"iY c #dea583",
"dS c #deaa31",
"#f c #deaa39",
".I c #deaa7b",
"cm c #deaa8b",
"et c #deaa94",
"dw c #deae41",
"fC c #deae9c",
"iS c #deaea4",
"lM c #deaeac",
"ey c #deb2ac",
"l0 c #deb2b4",
"lK c #deb6b4",
"fP c #deb6bd",
"i7 c #deb6de",
"kO c #debade",
"mX c #debede",
"iM c #ded6b4",
"g. c #ded6bd",
".b c #ded6c5",
"bh c #ded6d5",
"f0 c #ded6de",
"b9 c #dedac5",
".z c #dedacd",
"#5 c #dedad5",
"aV c #dedade",
"eF c #dedae6",
"b. c #dedecd",
".R c #deded5",
"cF c #dedede",
"h6 c #dee2e6",
"dK c #e68929",
"bk c #e68939",
"ca c #e68d31",
"d9 c #e68d52",
"gq c #e69139",
"dD c #e69141",
"#n c #e6914a",
"fa c #e69162",
"gH c #e69539",
"kf c #e69541",
"eI c #e6954a",
"#r c #e69552",
"jT c #e69562",
"lq c #e6956a",
"m. c #e695bd",
"cw c #e6995a",
"fW c #e6996a",
"l9 c #e69973",
"dL c #e69983",
"dG c #e699b4",
"ix c #e699cd",
"jB c #e69d73",
"gJ c #e69d8b",
"mK c #e69de6",
"l6 c #e6a18b",
"gF c #e6a1d5",
"ma c #e6a1de",
"hW c #e6a1e6",
"mI c #e6a5e6",
"la c #e6aa20",
"dQ c #e6aa6a",
"kU c #e6ae31",
"ej c #e6ae41",
"ci c #e6ae7b",
"#R c #e6ae83",
"gj c #e6b231",
"g7 c #e6b27b",
"#y c #e6b283",
".B c #e6b28b",
"en c #e6b294",
"aj c #e6b29c",
"h9 c #e6b2ac",
"ce c #e6b69c",
"fE c #e6b6ac",
"dW c #e6baa4",
"el c #e6baac",
"ju c #e6bac5",
"kV c #e6bacd",
"gi c #e6bec5",
"l1 c #e6becd",
"mC c #e6bee6",
"mf c #e6c2e6",
"mQ c #e6c6e6",
"de c #e6dac5",
"aC c #e6decd",
"#1 c #e6ded5",
"mP c #e6dee6",
"bM c #e6deee",
"fn c #e6e2cd",
".w c #e6e2d5",
".N c #e6e2de",
"bD c #e6e2e6",
"fU c #e6e2ee",
"dy c #e6e6d5",
"av c #e6e6e6",
"gE c #e6e6ee",
"kY c #e6eae6",
"d8 c #e6eaee",
"f9 c #e6eaf6",
"iP c #ee8d31",
"fb c #ee9141",
"dz c #ee9541",
"d6 c #ee954a",
"bE c #ee955a",
"h3 c #ee9941",
"jS c #ee994a",
"eH c #ee9952",
"#a c #ee9962",
"jF c #ee9d4a",
"kz c #ee9d52",
"hO c #ee9d5a",
"aA c #ee9d62",
".0 c #ee9d6a",
"bH c #ee9d7b",
"a. c #ee9db4",
"#0 c #eea16a",
".1 c #eea173",
"b8 c #eea17b",
"hR c #eea183",
"kH c #eea1de",
"kg c #eea583",
"gn c #eea5cd",
"eN c #eea5d5",
"f8 c #eea5de",
"h5 c #eea5e6",
"mk c #eea5ee",
"ja c #eeb639",
"gc c #eeb641",
"ad c #eeb68b",
"cK c #eeb694",
"jX c #eeba83",
"k9 c #eeba8b",
"aH c #eeba94",
".u c #eeba9c",
"gk c #eebe8b",
"fH c #eebe9c",
"eY c #eebeb4",
"iX c #eebec5",
"ia c #eebecd",
"ka c #eebed5",
"ge c #eec29c",
"cs c #eec2c5",
"co c #eec2cd",
"fs c #eec6cd",
"kJ c #eec6d5",
"ee c #eecade",
"hb c #eecae6",
"l7 c #eecaee",
"jR c #eee2cd",
".E c #eee2de",
"eg c #eee6d5",
"kA c #eee6de",
"ar c #eee6ee",
"jQ c #eee6f6",
"#L c #eeeade",
"#m c #eeeae6",
"#6 c #eeeaee",
"bG c #eeeaf6",
"f. c #eeeee6",
".# c #eeeeee",
".2 c #eeeef6",
"hP c #eeeeff",
"ga c #eef2f6",
"eJ c #eef2ff",
"jp c #f69952",
"ir c #f69d41",
"km c #f6a152",
"hd c #f6a15a",
"eL c #f6a162",
"bc c #f6a56a",
".M c #f6a573",
"fd c #f6a58b",
"#c c #f6a5bd",
".P c #f6a5c5",
"gR c #f6ba8b",
"lh c #f6be8b",
"k8 c #f6be94",
"#j c #f6be9c",
"hJ c #f6bea4",
"h# c #f6c294",
"k7 c #f6c29c",
"em c #f6c2a4",
".o c #f6c2ac",
"gU c #f6c2cd",
"li c #f6c69c",
"lg c #f6c6a4",
"eo c #f6c6ac",
"aD c #f6c6b4",
"eq c #f6c6bd",
"gl c #f6c6e6",
"f4 c #f6ca62",
"dE c #f6ca6a",
"cJ c #f6cab4",
".6 c #f6cabd",
"hN c #f6cac5",
"iw c #f6cad5",
"j0 c #f6caee",
"dV c #f6cecd",
"kZ c #f6ced5",
"e1 c #f6cede",
"hQ c #f6cee6",
"f6 c #f6ceee",
"hq c #f6cef6",
"aK c #f6d2de",
"io c #f6d2e6",
"d. c #f6d2ee",
"l3 c #f6d2f6",
"mY c #f6d6f6",
"a0 c #f6eee6",
".3 c #f6eeee",
"#o c #f6eef6",
"gK c #f6eeff",
"dJ c #f6f2e6",
"c# c #f6f2ee",
".L c #f6f2f6",
"#s c #f6f2ff",
"je c #f6f6ee",
".t c #f6f6f6",
"a# c #f6f6ff",
"#b c #f6faff",
"j4 c #ff0000",
"kX c #ff0008",
"iH c #ff0400",
"iE c #ff0408",
"i2 c #ff0808",
"#7 c #ffa56a",
"k6 c #ffaa62",
"fu c #ffae73",
"cf c #ffae7b",
"bo c #ffae8b",
"k5 c #ffb26a",
"dt c #ffb273",
"#z c #ffb28b",
"fM c #ffb67b",
"cj c #ffb683",
"#P c #ffb68b",
"h8 c #ffb6ac",
"kI c #ffb6b4",
"e3 c #ffb6ff",
"k3 c #ffba83",
"jr c #ffba8b",
".K c #ffba94",
".v c #ffbaa4",
"bV c #ffbaac",
"ev c #ffbab4",
"mV c #ffbaff",
"lj c #ffbe8b",
"#W c #ffbe94",
"ch c #ffbea4",
"eB c #ffbeb4",
"j7 c #ffbeff",
"d0 c #ffc294",
"bs c #ffc29c",
"bm c #ffc2a4",
"fx c #ffc2ff",
"k1 c #ffc694",
"iW c #ffc69c",
"bS c #ffc6a4",
"fw c #ffc6b4",
"cI c #ffc6bd",
"e9 c #ffc6ff",
"g# c #ffca6a",
"lm c #ffca9c",
"gS c #ffcaa4",
"am c #ffcaac",
"#S c #ffcab4",
"#l c #ffcac5",
"#C c #ffcaff",
"c3 c #ffce73",
".H c #ffce8b",
"cp c #ffceac",
"b7 c #ffceb4",
".j c #ffcebd",
".Q c #ffcec5",
"bQ c #ffcecd",
"aI c #ffceff",
"fS c #ffd27b",
"dv c #ffd2ac",
"dY c #ffd2b4",
"c7 c #ffd2bd",
"ac c #ffd2c5",
".X c #ffd2cd",
"bO c #ffd2d5",
"dn c #ffd2de",
"bz c #ffd2e6",
"hy c #ffd2ee",
".k c #ffd2ff",
"eh c #ffd683",
"b4 c #ffd68b",
"jz c #ffd6b4",
"bX c #ffd6bd",
"ah c #ffd6c5",
".4 c #ffd6cd",
"a2 c #ffd6d5",
"es c #ffd6de",
"cO c #ffd6ee",
"iZ c #ffd6f6",
".A c #ffd6ff",
"iN c #ffda83",
"d3 c #ffda8b",
"j. c #ffdabd",
"a9 c #ffdac5",
".g c #ffdacd",
".f c #ffdad5",
".y c #ffdade",
"aZ c #ffdae6",
"gW c #ffdaee",
"a6 c #ffdaf6",
"#U c #ffdaff",
"e6 c #ffdec5",
"gd c #ffdecd",
"ay c #ffded5",
"ba c #ffdede",
"#u c #ffdee6",
"#E c #ffdeee",
"cz c #ffdef6",
"#g c #ffdeff",
"j# c #ffe2d5",
"dq c #ffe2de",
".F c #ffe2e6",
".s c #ffe2ee",
"ag c #ffe2f6",
"#e c #ffe2ff",
"cn c #ffe6de",
"#Y c #ffe6e6",
"aF c #ffe6ee",
".d c #ffe6ff",
"ll c #ffeade",
"#v c #ffeae6",
"aM c #ffeaee",
"#w c #ffeaf6",
".D c #ffeaff",
"jn c #ffeee6",
"k0 c #ffeeee",
".c c #ffeef6",
".m c #ffeeff",
"it c #fff2ee",
"#J c #fff2f6",
".a c #fff2ff",
"#O c #fff6f6",
".i c #fff6ff",
".q c #fffaf6",
".n c #fffaff",
"Qt c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.c.dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.f.gQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.h.iQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.j.kQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.l.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.n.o.pQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.qQtQtQtQtQtQtQtQtQt.r.sQtQtQtQtQtQtQtQt.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.iQtQtQtQtQtQtQt.n.u.vQtQtQtQtQtQtQt.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.wQtQtQtQtQtQtQtQtQt.x.yQtQtQtQtQtQtQtQt.zQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.AQtQtQtQtQtQtQt.i.B.CQtQtQtQtQtQtQt.D.iQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQtQtQtQtQtQtQt.E.FQtQtQtQtQtQtQtQt.G.HQtQtQtQtQtQtQt.a.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.mQtQtQtQtQtQtQt.hQtQtQtQtQtQtQt.a.I.JQtQtQtQtQtQtQt.K.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQt.qQtQtQtQtQt.L.M.NQtQtQtQtQtQtQt.O.PQtQtQtQtQtQt.n.Q.RQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.AQtQtQtQtQtQtQt.S.aQtQtQtQtQtQt.m.T.UQtQtQtQtQtQtQt.VQtQtQtQtQtQtQt.DQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.WQtQtQtQtQtQt.X.YQtQtQtQtQtQtQt.Z.0.nQtQtQtQtQt.w.1.2QtQtQtQtQt.3.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.D.4.nQtQtQtQtQt.5.6QtQtQtQtQtQt.D.7.8QtQtQtQtQtQt.c.9QtQtQtQtQtQt.i.AQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQtQtQtQtQtQtQt.hQtQtQtQtQtQt.a#.QtQtQtQtQtQtQt###a#bQtQtQtQtQt.h#c.nQtQtQtQtQt#dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.dQtQtQtQtQtQt.F.YQtQtQtQtQt#e#f#gQtQtQtQtQt.d#h#iQtQtQtQtQtQt#j#kQtQtQtQtQt.D#l.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#mQtQtQtQtQt.b#n#oQtQtQtQtQt#p.DQtQtQtQtQtQt#q#r#sQtQtQtQtQt#t#uQtQtQtQtQt#v.JQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.D#wQtQtQtQtQtQt#x.aQtQtQtQt.i#y#zQtQtQtQtQt#g#A#xQtQtQtQtQt.d#B#CQtQtQtQtQt#D#EQtQtQtQtQtQt.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#FQtQtQtQtQtQt#c.SQtQtQtQtQt#G#a.nQtQtQtQtQt#H#I.2QtQtQtQt#J#K.iQtQtQtQt#L#M#NQtQtQtQtQt#O.n.qQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.a#PQtQtQtQtQt#Q#R.mQtQtQtQt#S#TQtQtQtQtQt#U#A#VQtQtQtQtQt#W#X#eQtQtQtQt#Y#ZQtQtQtQtQtQt.i.kQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.tQtQtQtQtQt#o#0#1QtQtQtQtQt#2.mQtQtQtQt#3#4#5QtQtQtQt.n#H#M#6QtQtQtQt#7#8QtQtQtQtQt#9a.a#QtQtQtQtQtaaQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.a.n.nQtQtQtQtQtabacQtQtQtQt.iadaeQtQtQtQt.mafagQtQtQtQtah#A#TQtQtQtQtQtaiaj.aQtQtQt#eakalQtQtQtQtQtam.y.iQtQtQtQtQt.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtan.nQtQtQtQtQtQtaoQtQtQtQtQtapaqarQtQtQt.RasatQtQtQtQt.a#HauavQtQtQt#mawaxQtQtQtQtayaz.aQtQtQtQt.qaAaBQtQtQtQtQtaCQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.hQtQtQtQtQtQtaDapQtQtQtQt.iaEaFQtQtQtQtaGaH.iQtQtQtaIaJ#2QtQtQtQtQtafaKQtQtQtQt#9aL.dQtQtQtQtaM.8QtQtQtQtQt#U.iQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.aaNQtQtQtQtQtaOaPavQtQtQt#6aQaRQtQtQt.LaS#2QtQtQtQt#waTaUaVQtQtQtaWaXaYQtQtQt#1afaxQtQtQtQtQt#taZQtQtQtQta0.X#6QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQtQtQtQtQtQtQt.iaDa1QtQtQtQtQt#Za2QtQtQtQtaR.7.dQtQtQta3aka2QtQtQt#Qa4a5.nQtQtQtacaf.mQtQtQtayaTa6QtQtQtQta7a8#gQtQtQtQta9alQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtb.QtQtQtQtQtQtQtb##r#mQtQtQtQta2#2QtQtQtQtbabb.sQtQtQtbcbdagQtQtQt#YaTbe#NQtQtQtbfbgbhQtQtQt#9bibjQtQtQt.tbkblQtQtQtQt.n#.QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbmQtQtQtQtQtQtQtae#SQtQtQtQt#ebnboQtQtQt#UbpbqQtQtQt.hbratQtQtQtbsbtbu.iQtQt.abvbwQtQtQt#ebxbyQtQtQtQt#v#K.mQtQtQtQt#tbzQtQtQtQtQtQtQtQt.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbAQtQtQtQtQtQtQtbwaMQtQtQtQtbBaq#6QtQtQt#VbCbDQtQt.FbdbEa#QtQtayaTbCbFQtQtQt#H#IbGQtQtbabdbH.nQtQtQtbIbJbGQtQtQtbKbLbMQtQtQtQtQtQtQtbNQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.m.VQtQtQtQtQtQtbObPQtQtQtQt.maf.yQtQtQtbQbb.sQtQt.k#AbPQtQtQt#daJbR.mQtQtbSbT#iQtQtQt#9bUbVQtQtQtbSbUbWQtQtQtbXbYbZQtQtQtQtQtQtQtbAQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nbQb0QtQtQtQtQt#6#M#DQtQtQt#s#n.OQtQtQtbNb1bfQtQtQtb2b3b#QtQtb4aTb5b6QtQtb7bdb8.nQtb9b5c..iQtQtc#cacbQtQtQt.3cccdQtQtQtQtQtQtQtaR.dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.dQtQtQtQtQtQtQt.DcecfQtQtQtQtQtcgak#SQtQtQtchbt#FQtQtQtb2.7#eQt.mciaT.sQtQtcjbtaf.dQtQtckbTclQtQtacbbcm.DQtQtcnbbco.nQtQtcpcq#UQtQtQtQtQtQtcrcs.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtctQtQtQtQtQtQtQt#5cu#dQtQtQtQtQt#.cvavQtQtQta5aq#6Qt#bcwaTaZQtQtbfcx.SQtQtacaTb5cyQt.LaPaTczQtQtcAb1cBQtQtQtcC#KcDQtQt.iaTbJarQtQtQtQtQtckcEcFQtQtQtQtQtc#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.S.iQtQtQtQtQtQtb6cGbSQtQtQtQt.acH.oQtQtQtcIbb#uQtQt#PbT.xQtQtcJbbcK.iQtcLa4af#EQtQtbRcMcNQt#U#AaTcOQtQtcPcQcRQtQtQtcScTcUQtQtQtQtQtcVcWcXQtQtQtQtQt.m.F.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtaRay.nQtQtQtQtQtcYcZc0QtQtQta#.1aT.cQtQtc1as.GQtQt.a#Hb3#5QtaaaTc2QtQtc3bbb5c4Qtc0c5c6.nQtc7c8c9bFQt.taSbbd.QtQtd#b1daQtQtQtQtQtdbdcddQtQtQtQtQtde#0aBQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdfam.iQtQtQtQtQtdgdh#UQtQtQt#gdidjQtQtQt.xdkbmQt.mdlaTa2QtaF#HcGb#Qtdmbt#HdnQt.gbbdo#eQtaiaJdpQtQtdqaTdr#gQtb7aJds.DQtQtQtQtdtbTduQtQtQtQtQtdvdwdxQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtdyQtQtQtQtQtQtQtQtQtbydz#mQtQtQtQtQt#8dA.NQtQtQtdBaTdCQtQtagaTdD#oQtbBb1#VQt.bb5#H#uQtdEaT#H#kQtcVaTdFQtb9b5aTdG.nQtdHb1dIQtdJdKbddL#sQtQtQtdMb1dN.nQtQtQtQtdObedPQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbSQtQtQtQtQtQtQtQt.nc2dQ#UQtQtQtQt.Daz#y.DQtQtQtdRbt#QQt.DdSaTaFQt.FaTak#UQt##btdTQtdUdk#HdV.iadbbdW.ib7aTa4dXQt#WbTc..aQtdYbbdZ#CQtQtQtd0#Ad1#eQtQtQtQtdtbUd2QtQtQtQtQtQtQtQtQt#eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Sd3.3QtQtQtQtQtQt.id4#4d5QtQtQt.ndnbdd6.3QtQt#EaTaqavQt.Sbbd7Qt#5b3aTbOd8aqaTd9.2bcaTc5e.Qte#aX.9Qtdjc5bg.ac#ccaTea#s.n#H#HebQtQtQtecedcqee.iQtQtQtcVcxefQtQtQtQtQtQtQtegeh.pQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQteiejdYQtQtQtQtQtQt.nekbtcjQtQtQt.aelbdem.nQt.menbdeoQt.nbRbt.pQt.Gbt#xQtepbta5QtdUaJ#HeqaIeraTesb7#A#Het.DcnaTeuevQtewaJex.iQtQtcp#AaTey.dQtQtQtezbUeAQtQtQtQtQtQtQta7.BeBQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQteCaUeDQtQtQtQtQtQt.i#8b1eEQtQtQteF#Mbd.j.nQteGb3#H#wa#eHbbeIeJ#laTb3b6bcaTb5eKeLaTc5eies#Hb5aY#SaT#HeMQtcCaT#8QtbKaTaTeN#bQta1awaTeOePQtQtQtaicxdN.iQtQtQtQtQtQtckeQeRQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#CeS##ay.iQtQtQtQt.iekbTeTQtQtQtaIbnaT.4QtQt.9bTdHQteUa4eV.mcN#AaT.6.JaJeVbOeWaJeXeYeZaJbucOe0#A#Hcz#FaJafe1.W#A#HeS#UQt.AcG#He2e3QtQt#Je4bTe5.mQtQtQtQt.ne6e7e8e9QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta0Qtf.QtQtQtQtQtQtQtQtQtf#fabdfb.bQtQtQtQt.id4cxbP.nQtQteC#H#HaFQt.nbub1eEQt.Gb1bfQtfced.Gfdfec5.8#n#Hc5fffg#Hfhfib5eXbefjca#HfkflcaaTasfmQtfncvaTafebQtQt#ve7fofp#eQtQtQtQtaCd6bdfqePQtQtQtQtQtQtQtQtQt.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.d.FfrQt.nQtQtQtQtQtQtQt.Dfsft#AfuQtQtQtQt.iekbT##aMQtQtfvbtbR.aQtbQaT#AfwesaT#hfx.uaT#hfy#AaTfzdFfAfBfCfDfAcdfEafbTfFeYaTaJfGfH#HbxfIQt.dfJ#Ha4fKQtQt.g#HaJfL#U.nQtQtQtfMfNfOfP#gQtQtQtQtQtQtQtQtQta1.a.iQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.L.mfQeLfRQtQtQtQtQtQtQta##ecbb1aGdq#OQtQt.idFb1#HfS.nQtfTaT##.ifUcuaTaPaYfVaT#re.azd1fWfyfXfY.DfZ#ef0.nf1.i#5a6f2#ef3bLexeN#2edcHd..wdKaT#HeO.a#Of4aTf5d1f6a#QtQt#JcCb1f7f8f9QtQtQtQtQtQtQtg.g##i.dgaQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtgbaL.Oay.aQtQtQtQtQtQt.afFbTaTgcgdQtQt.neka4aTge.a.ia5aJgfQteB#A#HcedgbUgg.Dev.d.dQtQtQtQtQt.mQt#U.i.k.n#eQt.mQt.dQt.i.aghgi.kgjaTbx#K#e.mgkaTbxazgl.iQt.aameXbtgm.A.iQtQtQtQtQt.i#vbIe2bl.n.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQteFgnc.cvgoQtQtQtQtQtQtQtghgpc8awaNQtQt.id4edaTgq#5czafaTgr.i#xaTc.d.gsQtQtQtQtQtgtgugvgwgxgygzgAgAgAgAgBgCgxgwgvgD.AgEQtQtQtfvcbftgFgGgHaTgIcHgJgKQtfRgLaTedgM#e.nQtQtQtQtQtgNgLbdgOgPQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.i.ighgQafgRgSQtQtQtQtQtgTdZ#HcQdjaMQt.iekaJaTfJcggU#HaJgVgWgX#U.iQtQt.dgYgZgBg0g0g1g0g0g0g2g0g3g0g4g1g0g0g3g0g3g0gCg5g6bFQt#g.D#Ug7bbbx#HfP.mQtg8a4#Hg9h..iQtQtQtQtdvh###brhahb#eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.qQtc#QtQtQtQtQtQtQtQtQtQtQtQtQthceacqb1aiay#mQtQtQtf1bL#H#HaThd.w.aekc5#Hhee.hfc8hgbjQtQtQthhhig0g0g0g0g0g0g0g0g0g0g0g0g0g0g0hjhkhlhmhnhog4g0g0g0gAhphq.LQtdxcEazhrhscn##c5eXhthuQtQtQtf.dqgVc5bbhvhw.Da#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.m.actaM.AQtQtQtQtQtQtQtQtQtQtQt.m#ecRbUbbhxbKQt.nQt#gelafbxaThxcj#e#Z#AeXeughhy#gQtcDhzhAg0g0hBhCgCg0hDg0g0g0g0g0g0g0g0g0g3g0hE#UQtQtQt.khFhGgyg0g0g0hHhIQt.a.D.AhJbbbx#HcWhKQtQtQtbKhL#HcQfBhMe3QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.aQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#bQteKhNa3hOdM#J#LQtQtQtQtQtQtQtQtQtbZcEcqaT#Hd6fRQthPhQc.gI#Hc5cAhRhSbieA.nQt.dhTg1g0g0gyhUf1hVg0g0g0g0g0g0g0g0g0g0g0g0g0g0g0gyhcQtQtQtQtQt#6hWhXhBg0g0hYhl.LQtcyhZaTh0h1Qth2h3#HaT#Hash4h5h6QtQtQtQtQtQtQtQtQtQtQtc#Qth7baab.i.tQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.aQth8h9i.cGgVbXdYQtQtQtQtQtQtQt.dhQexg9aTg9dja9#e#eekaJi#aJafiaibQt#gicg0g0g0hYidQtQt#Ug1g1g0g0g0g3ieifigihiiijg0g3g0g2g0ik#eQtQtQtQtQtQtQt#Cilg0g0g0iminQt#giofZc7e#bt#H#A#Hiphw.a.nQtQtQtQtQtQtQt.nQtdYbX#9diekcoe9Qt.nQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbG.acliqd1af##irisit#mQtQtQtQt.nbliuaTc5aTcviviwcdaTd1ix#6QtiygCg0g0iziA#6QtQtQtiBg0g0g0g0iCiDiEiFiEiGiHiIiJg0g3g0g0g0gvQtQtQtQtQtQtQtQtQt.diKg0g0g1iLQtQtQtdgb1#HgIfBgOgPQtQtQtQtQt.nQtiMiNiOiPe7cHiQiRfY.i.2QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.m.acliSf7iTaTiUiVb7iWQtQtQt.AiXfLaJeXaJi#iYeb.D.niZiBg1g0gyidQtQtQtQtQti0g0g0g1g0i1iHi2iFiEiHiEi3iEiHi4g2i5g0g0g1.dQtQtQtQtQtQtQtQtQtQtgPi6g0g3gyi7QtQti8e2i9f6.dQtQtQtj.j#dUjajb#AbbjciQjdf2.a.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtjeQtc#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtd8.Dfmiqhvc8bbfojfdzgN.cb##Udac9aTdsjgQth6hmg1g0g1jhaVQtQtQtQtQt.Lgxg0g0g0g2jiiEjjiHjjiEjjiHjjiHiGjkg0g3g0g0hmQtQtQtQtQtQtQtQtQtQtQt.#jlgzg0g0iKePQtjm.aaCjnjojpe4b5aTfoaTaTf7gOjq.dgEQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#OQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#UaM#F.fjrj#js#O#gQt.iQtQtQtQtQtQtQtQtQtQtQt.D.mjgjtc.g9aTbT#Hhxai.ufKjuaIQthIjvg0g1iz.dQtQtQtQtQtQtQt.dg0g1g0g2jwiEi3iEiEiHjjiEiHiEiFiEiHjxg0g0g0hj.nQtQtQtQtQtQtQtQtQtQtQtQt.ahXg3g0hAgY.nQt.cbgbTaTbxeXg9jyhMjq#e.dQtQtQtQtQtQtQtQtQtQtQt.aQtjzjncPaFam.n.aQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta#Qtb#.djAjBjCjDjEfVaijFjGiNecitb9Qta0Qt.nQtQtQthP.addiRfLaf#Hc5fOiwhsjHhog0g0g0g0gBgDQtQtQtQtQtQtQtjIg0g0g0g0i3i3iEjJiHjjiEjKiEjjiHjjiHiJg0g0g0gzQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtjLizg0g2gzjMjN#gfFjOdsgOjP.djQQtQtQtQtQt.tQtjR.ia7iNdbjS#taUekjTjUagbjQt#bQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.aQtbF#UjVeyeOjWbdbTaTaJi#iUcCjXcVc7ec#J#gQt#U#ejYjZfIj0.ij1g0i5g0g3g0g3g0g0j2#UQtQtQtQtQtg6g0g0g0ijj3iEj4iEiFiEiHiEjJiEiHiEiHj5g0g0g0g4fxQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.ij6g0i5g0gBbjQtj7.d#eQt.iQte6jncjamj8dQj9bxaTbUfOk.k#kaev.a.dQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtgaQteP#gf2kbkckdfBaTbbcxbb#H#Hke##gLgrkfdFkg.LQtkhg0g0g0g0g0g0g0g0g0g4ki.#QtQtQtkjg0g0g0g2iHi3iEjjiEjKiEjjiHjjiHjjiHiDg0g0g0g0#gQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQthhgAg0g0kk.DQtQtklkmgVccjfb5#Hb1bdaTcqkne5kof2#ghsQta#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.iQtkp#efYgifKkqdsg9aTaJ#HaJ#H#Ai#c7.n.ahGhAg0g0g0g3g0g0g0g3g0krfxQtQtj1g0g0g0g2ksiEi3iEiHiEjKiEiHiEjKiEj4j3g0g0g0g4bFQtQtQtQtQtQtQtQtQtQtQtQtQtQt.Dktg0g0gAkug6.ditcCdkaTaJaTbtc8ipkvkwebiZcDQt.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQta#Qths.dkxdLkyhgdsazaTedbdkzkAQtkBhXg0g0g0g0g0g0g0g0g0gAkjQtjNg0g0g0g0kCi4iHjjiEjjiHjjiEjjiHiFiHkDg0g0g0gBQtQtQtQtQtQtQtQtQtQtQtQtQtQtkEkkg0g0gxkF.n.wg#aTaTaTkGd1gMeAkHin.igEQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQt#g.mkIkJgXkKfLce.DQt.dkLkMhDg0g3g0g4g0g0g0g0kNkOgzg0g0g1kPiEiHiEjKiEiHiEi3iEiEiEiIkQg0g0g0gZQtQtQtQtQtQtQtQtQtQtQtQt.dkRg0g0gAkSkTQtjzkUfBkqkykVgt.D#gQt.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQt.nQt.nQt.qQt.3Qtbj#edP.a.3Qt.n.diKg0g0g0g0g3g0g0g0g0gAg1g0g0g0g0kWiHjKiEjKiEjKiHiFkXiFiig0g0g0g0kFQtQtQtQtQtQtQtQtQtQtQtgPhYg0g0izhlkYQt#mkZhK#UbjQt#sQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.mQt#g.nbX#Jcpk0fR#vk1j#k2gdk3j.k4jzk5dvbKcpk6gSdUbScVk7g8k8j8k9ezjXl.jal#g7aikUcCdQe0ladjfJjb#hcVQtQtQtkFlbg0g1g0g0g0g0g0g0g0g0g0g2g0ijlciEj4iEi3iEiHiEjKldg0g0g0g0gyQtQtQtQtQtQtQtQtQtQtQtlegAg0g1lf#g.nQt#UlgcA#yezlhj8k7eDlicVgSk6cpbKdYfuc7jogdljj#lklllmjnh2itdv.ij.Qt.dQt.mQtQtQtQtQtQt",
"QtQtQtQtQtQt#OQt.w.iln.slodne.b8lplqcRlrlsh0jyjyf7ltlulvfOlwbdbdbdcxbdbbbdb1bdaTbbb1aTaTaTc5#Hc5eXgI#HgI#HgIfeaT.O.aQtQteRlxg0g0g0g0g0g0g0g0g0g0g0g0g0g0kPlylziEjjiElAlBg0g2g0g0g0lCQtQtQtQtQtQtQtQtQthWhYg0g0lDkhQt.tk0ezb5aTgIeXc5#Hc5aTb1aTaTbdcxbdlElFcxbdbdlFlwfOlGf7kdh4lHkylqfvkg.C.saO.n#mQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.nQt.iQt.aQt.mQt.dQt#g.n.A.abF.Dfx#efZiZlIhQf2kJd2gilJlKlLlMfKlNdNe8eOlOfplPdsiphvgQftfAaflQaT.j.iQt.DkOimg1g0g0g0g0g0g0g0g0g0g0g0g0g0ielRlSijg0g0g3g0hDg0kSQtQtQtQtQtQtQtQtgthEg0g0g0lTlUQtlVdQaTbT#Hg9cHgQhvlWlXlYexlZdNjdfKl0dul1d2eel2l3fZ#gfx.mbj.n#gQt.DQt.aQt.iQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQtQtQta#Qt#oQt#6QtfUQtf#.il4.mkT.deR#Ul5d.l2h5jYl6jAQtQtQt.n.igYgyg0g0g0g0g0g0g0g3g0g0g0g0g0g0g0g0g0g0g0g0g0iL.tQtQtQtQtQt#Nl7iKg0g0g0g1l8#NQtaWl9dam.m#mambf6bZ#gcU.dmc.ifUQtfUQtbGQtQtQt.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtgtQtQtQt.il3bjQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.nQtQtQtQtQtQtQte9mdkMg0g0g0g0g0g0g0g0g0g0g0g0g0g0g1g0g0g0gymemfhIj1leilizgAg0g0g0g0gAmg.dQtQtQt.aQt.iQtQtQtQtQtQtQtQtQt.ml3.AQtQtQt.Al3.DQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtgtg0gYQtQt.Dg0hT.nQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.t.dmhmig0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g1g0g0gAkF.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtl3g0hUQtQtQtmjg0mkQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtl3g0mlQtQtf1g0hXQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbji7hTizg0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g4g0g0lDmmlDg0gyi7.mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbFmnhIQtQtQthmg0jLQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtgPiLf1Qt#NgvjNQtavhUjLQtQtQtQtl7l8gvhTmoQtQtlUg0l8QtQt.dg0g5.LQtQtQtmpjMiLjhhhQtQt.ahUmqiLmqkhQtQtQtQtQtQtQtmri0ms.a.nQtQtQtQtQtQtQtcDmthmhXizgAg0g0g0g0g0g0g0g0g0g0g0hAgxiLkhiLlDg0gxhq.tQt.tmugvmql8#eQtQtQtQtlUjMiLjhhhQtQt.ahpkEQtQtkFizg0kugv.mQtQt.LmogvgvhG.AQtQtgtiLgvhUhIQtQtQtQtQtQtQt",
"QtQtQtQtQtQtj1g0mvQtl3g0kSQt.mg0mw.nQtQtmxg0gAlDgBmqQtQthqg0mlQtQtfxg0hXQtQtQthmg0gAgygBmn.iQtmyg0g4gChAg0hjQtQtQt.nmzgzg0g0g0g0mAe9QtQtQtQtQtQtQtQtQt.d.mgtkOgDmBjMkSgvkSjMmBgDmCj7QtmDgZg0g0mE#eQtQtQtQtmig0gzg4gB.mQtQtmhg0g4gyhAmn.aQtjNg0gvQt.nmFg0g4gzgyjNQt.amGg0hAgCgChhQtQtmgg0gAg4g1khQtQtQtQtQtQt",
"QtQtQtQtQtQtkFg0kFQtlUg0iLQtcDg0iKQtQt.Dg0gxmp.dhc.n.nQtlUg0l8QtQt.dg0iK.LQthcg0homkhc.daVQtQtmkg0iKhc#ekNg0lUQtQtmHg0g0g0kMhGkhgvgweRQtQtQtQtQtQtQtQtQtQtQtQtQt.LQt.#Qt.#Qt.tQtQtQtkhhAg0g4iL.mQtQtQtQtarizlDl7iLg0msQtbFg1izmIhc.d#NQtQtl7g0iLQtQtavhTg0mJcDQtQthlg0iKgt.dhcQtQtQtgYg0mhmKg0gw.LQtQtQtQtQt",
"QtQtQtQtQtQtg6g0j1Qtl3g0mLQt.mg0mM.iQtkFg0gylTiKgwi0QtQthqg0mlQtQtf1g0hXQtQthFg0kMgwmGgwmNQtQtmpg0gvQtQtmBg0mCQt.ngzg0g0ktl5Qt.nQtf1mx.DQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.mmvkMg0g0lDkhQtQtQtQtQtQtQthYiz.dl3gxmfQtkOg0gygwmGgwmNQtQtjNg0iLQtQtQthmg0jLQtQtQthGg0mimGg5lTlUQtQtmxg0mC.mgZiLQtQtQtQtQtQt",
"QtQtQtQtQtQtkFg0kFQtgtg0gvQtcDg0iKQtQtjlg0gChohogyhm.LQtlUg0l8QtQt.dg0iK.tQtgDg0lDgxizkMgvQtQtmkg0iLQtQtgYg0jLQtlUg0g0gAjNQtQtQtQtQtmr#gQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtjLizg0g0g0gxmOQtQtQtQtQtQtQt#6izkMQt.t.n#6QtkFg0gBmiizgygvQtQtl7g0iLQtQtQtjMg0kEQtQt.niKg0hYhohokMhlQtQtmhg0msQtmPQt.nQtQtQtQtQt",
"QtQtQtQtQtQthFg0mgQtl3g0kSQt.mg0mw.iQtmrg4ku.D.A.i.dQtQthqg0mlQtQtfxg0hXQtQtmQg0hEe9.n#NQtQtQtmpg4iLQtQtmBg0kOQtl3g0g0hY.nQtQtQtQtQtQt.DQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.mi7iBg0g0g0g0ilf1QtQtQtQtQtQtQtQtQthYiz#gQtQtQtQtl7g0kuf1.n.AQtQtQtjNg0iLQtQtQtjMg0hhQtQtQthmg0gv.i.A.n.DQtQtmxg0kOQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtf1hAgAgwiBg0gCg5mRg0iKQtQtQtkNg0iBmSgwlCQtQtjNg0l8QtQt#eg0hX.LQtavktg0hjiKgwmuQtQtmIg0iLQtQtmjg0msQtmThAg0gBbjQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtkhizg0g0g0g0gygucFQtQtQtQtQtQtQtQtQtarhYkMQtQtQtQtQtargwg0imiKhXkjQtQtl7g0iLQtQtQtidg0gCgw.dQt.dkMg1ktiKgwhqQtQtmhg0hIQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtmekuizikimgxizikhomB.nQtQt.mhGhHizgyl8QtQt#eiBg6QtQtbjmmhmQtQtQte9mUgxizgykS.aQtmVgxkhQtQthFhohqQtQtgvg4g0mvQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQte9mBgyg0g0g0g0g4gwl3.aQtQtQtQtQtQtQtQtQtQtQthTmw#eQtQtQtQtQtmTmLmiizgykS.aQteRkrkhQtQtQt#ekShoiklUQtQtl3gwmiizhYhIQtQti7mihqQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtbD.nbj.ibj.ibj.iavQtQtQtQtQtaV.ibjQt.nQt.tQtavQtQtQtcFQt.nQtQtQt.L.n#N.ibDQtQtQtaVQtQtQt.LQt.#QtQt.niBg0lD#gQtQtQtQtQtQtQtQtQtQtQtQtQtQt#NmWktg1g0g0g0g0g0hogD.nQtQtQtQtQtQtQtQtQtQtQtQt.nQtcFQtQtQtQtQtQtQt.LQt#N.ibDQtQtQtcFQtQtQtQtQt.L.n#NQtQtQtQtQt#N.i#NQtQtQt.LQt.#QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#UkMg0lDmX.aQtQtQtQtQtQtQtQtQtj7g6kNgAg0g1g0g0g0g0gChze9QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQthqgyg0g0hohmhWgt#UlUiAgYgwlDg0g0g0g0g0g0g0g0hAhTl3#6QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#Uktg0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g0g4gymnmpQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtkjmig0g0g0g0g0g0g0g0g0g0g0g0gzkNmh#g#6QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtcDg6hXmigBg4g1g4gAgCgxlTgYl7.AQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtbFmYmphWmOl7in.mavQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};


/* 
 *  Constructs a WellenreiterBase which is a child of 'parent', with the 
 *  name 'name' and widget flags set to 'f' 
 */
WellenreiterBase::WellenreiterBase( QWidget* parent,  const char* name, WFlags fl )
    : QWidget( parent, name, fl )
{
    QPixmap image0( ( const char** ) image0_data );
    if ( !name )
	setName( "WellenreiterBase" );
    resize( 191, 294 ); 
    setCaption( tr( "Wellenreiter" ) );
    WellenreiterBaseLayout = new QVBoxLayout( this ); 
    WellenreiterBaseLayout->setSpacing( 2 );
    WellenreiterBaseLayout->setMargin( 0 );

    TabWidget = new OTabWidget( this, "TabWidget", OTabWidget::Global );

    ap = new QWidget( TabWidget, "ap" );
    apLayout = new QVBoxLayout( ap ); 
    apLayout->setSpacing( 2 );
    apLayout->setMargin( 2 );

    netview = new QListView( ap, "netview" );
    netview->addColumn( tr( "SSID" ) );
    netview->addColumn( tr( "Sig" ) );
    netview->addColumn( tr( "AP" ) );
    netview->addColumn( tr( "Chn" ) );
    netview->addColumn( tr( "W" ) );
    netview->addColumn( tr( "T" ) );
    netview->setFrameShape( QListView::StyledPanel );
    netview->setFrameShadow( QListView::Sunken );
    netview->setRootIsDecorated( TRUE );
    apLayout->addWidget( netview );
    TabWidget->addTab( ap, "wellenreiter/networks", tr( "Networks" ) );

    Log = new QWidget( TabWidget, "Log" );
    LogLayout = new QVBoxLayout( Log ); 
    LogLayout->setSpacing( 2 );
    LogLayout->setMargin( 2 );

    Log_2 = new QMultiLineEdit( Log, "Log_2" );
    Log_2->setText( tr( "11/18 18:15 - log started\n"
"11/19 20:13 - new net : \"ELAN\"\n"
"11/19 20:15 - new station : \"pegasus\"" ) );
    LogLayout->addWidget( Log_2 );
    TabWidget->addTab( Log, "wellenreiter/log", tr( "Log" ) );

    tab = new QWidget( TabWidget, "tab" );
    tabLayout = new QGridLayout( tab ); 
    tabLayout->setSpacing( 2 );
    tabLayout->setMargin( 2 );

    Log_2_2 = new QMultiLineEdit( tab, "Log_2_2" );
    QPalette pal;
    QColorGroup cg;
    cg.setColor( QColorGroup::Foreground, white );
    cg.setColor( QColorGroup::Button, QColor( 192, 192, 192) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 223, 223, 223) );
    cg.setColor( QColorGroup::Dark, QColor( 96, 96, 96) );
    cg.setColor( QColorGroup::Mid, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Text, white );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, white );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, white );
    cg.setColor( QColorGroup::Button, QColor( 192, 192, 192) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 220, 220, 220) );
    cg.setColor( QColorGroup::Dark, QColor( 96, 96, 96) );
    cg.setColor( QColorGroup::Mid, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Text, white );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, white );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 192, 192, 192) );
    cg.setColor( QColorGroup::Light, white );
    cg.setColor( QColorGroup::Midlight, QColor( 220, 220, 220) );
    cg.setColor( QColorGroup::Dark, QColor( 96, 96, 96) );
    cg.setColor( QColorGroup::Mid, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Text, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 0, 128) );
    cg.setColor( QColorGroup::HighlightedText, white );
    pal.setDisabled( cg );
    Log_2_2->setPalette( pal );
    QFont Log_2_2_font(  Log_2_2->font() );
    Log_2_2_font.setFamily( "adobe-courier" );
    Log_2_2_font.setPointSize( 8 );
    Log_2_2->setFont( Log_2_2_font ); 
    Log_2_2->setText( tr( "00 0a 20 00 a8 00 e2 00 ...ESD..\n"
"00 0a 20 00 a8 00 e2 00 .*&23...\n"
"00 0a 20 00 a8 00 e2 00 ........\n"
"00 0a 20 00 a8 00 e2 00 ........\n"
"00 0a 20 00 a8 00 e2 00 ........\n"
"00 0a 20 00 a8 00 e2 00 ...BRA22" ) );

    tabLayout->addWidget( Log_2_2, 0, 0 );
    TabWidget->addTab( tab, "wellenreiter/hex", tr( "Hex" ) );

    about = new QWidget( TabWidget, "about" );
    aboutLayout = new QGridLayout( about ); 
    aboutLayout->setSpacing( 6 );
    aboutLayout->setMargin( 11 );

    PixmapLabel1_3_2 = new QLabel( about, "PixmapLabel1_3_2" );
    PixmapLabel1_3_2->setSizePolicy( QSizePolicy( (QSizePolicy::SizeType)0, (QSizePolicy::SizeType)0, PixmapLabel1_3_2->sizePolicy().hasHeightForWidth() ) );
    PixmapLabel1_3_2->setFrameShape( QLabel::Panel );
    PixmapLabel1_3_2->setFrameShadow( QLabel::Sunken );
    PixmapLabel1_3_2->setLineWidth( 2 );
    PixmapLabel1_3_2->setMargin( 0 );
    PixmapLabel1_3_2->setMidLineWidth( 0 );
    PixmapLabel1_3_2->setPixmap( image0 );
    PixmapLabel1_3_2->setScaledContents( TRUE );
    PixmapLabel1_3_2->setAlignment( int( QLabel::AlignCenter ) );

    aboutLayout->addWidget( PixmapLabel1_3_2, 0, 0 );

    TextLabel1_4_2 = new QLabel( about, "TextLabel1_4_2" );
    QFont TextLabel1_4_2_font(  TextLabel1_4_2->font() );
    TextLabel1_4_2_font.setFamily( "adobe-helvetica" );
    TextLabel1_4_2_font.setPointSize( 10 );
    TextLabel1_4_2->setFont( TextLabel1_4_2_font ); 
    TextLabel1_4_2->setText( tr( "<p align=center>\n"
"<hr>\n"
"Max Moser<br>\n"
"Martin J. Muench<br>\n"
"Michael Lauer<br><hr>\n"
"<b>www.remote-exploit.org</b>\n"
"</p>" ) );
    TextLabel1_4_2->setAlignment( int( QLabel::AlignCenter ) );

    aboutLayout->addWidget( TextLabel1_4_2, 1, 0 );
    TabWidget->addTab( about, "wellenreiter/about", tr( "About" ) );
    WellenreiterBaseLayout->addWidget( TabWidget );

    button = new QPushButton( this, "button" );
    button->setSizePolicy( QSizePolicy( (QSizePolicy::SizeType)1, (QSizePolicy::SizeType)0, button->sizePolicy().hasHeightForWidth() ) );
    button->setText( tr( "Start Scanning" ) );
    WellenreiterBaseLayout->addWidget( button );

    // tab order
    setTabOrder( button, netview );
    setTabOrder( netview, TabWidget );
    
    TabWidget->setCurrentTab( tr( "Networks" ) );

}

/*  
 *  Destroys the object and frees any allocated resources
 */
WellenreiterBase::~WellenreiterBase()
{
    // no need to delete child widgets, Qt does it all for us
}

/*  
 *  Main event handler. Reimplemented to handle application
 *  font changes
 */
bool WellenreiterBase::event( QEvent* ev )
{
    bool ret = QWidget::event( ev ); 
    if ( ev->type() == QEvent::ApplicationFontChange ) {
	QFont Log_2_font(  Log_2->font() );
	Log_2_font.setFamily( "adobe-courier" );
	Log_2_font.setPointSize( 8 );
	Log_2->setFont( Log_2_font ); 
	QFont TextLabel1_4_2_font(  TextLabel1_4_2->font() );
	TextLabel1_4_2_font.setFamily( "adobe-helvetica" );
	TextLabel1_4_2_font.setPointSize( 10 );
	TextLabel1_4_2->setFont( TextLabel1_4_2_font ); 
    }
    return ret;
}

