#!/bin/sh

# $1 appname
# $2 AppName
# $3 Icon
# $4 filename to output

echo "<html><head><title>$2</title></head><body>" > $4
echo "<img src=\"$3.png\">" >> $4
echo "<h1>$2</h1>" >> $4

echo "<P align=\"center\">FIXME Description<br>" >> $4
echo "<ul align=\"left\">" >> $4
echo "<li><a href=\"$1/about.html\">About</a></li>" >> $4
echo "</ul>" >> $4
echo "</body></html>" >> $4
mkdir $OPIEDIR/help/en/html/$1



