TEMPLATE	= lib
CONFIG		+= qt warn_on release
HEADERS	=	sdmon.h sdmonimpl.h
SOURCES	=	sdmon.cpp sdmonimpl.cpp
TARGET		= sdmonapplet
DESTDIR		= $(OPIEDIR)/plugins/applets
INCLUDEPATH += $(OPIEDIR)/include
DEPENDPATH      += $(OPIEDIR)/include ../taskbar
LIBS            += -lqpe
VERSION		= 1.0.0
