TEMPLATE        = lib
CONFIG          += qte warn_on release
HEADERS 	= device.h manager.h remotedevice.h services.h
SOURCES		= device.cc manager.cc remotedevice.cc services.cc
TARGET		= opietooth
INCLUDEPATH += $(OPIEDIR)/include
DESTDIR         = $(QTDIR)/lib$(PROJMAK)
LIBS += -lopie
#VERSION = 0.0.0
