#!/usr/bin/make -f
export OPIEDIR:=$(shell pwd)
export TOPDIR:=$(OPIEDIR)

export QMAKESPECSDIR=$(OPIEDIR)/mkspecs
export QMAKESPEC=$(QMAKESPECSDIR)/qws/linux-generic-g++

all :

clean-configs : $(TOPDIR)/.depends
	@echo "Wiping generated config.in files..."
	@-rm -f $(configs)

-include $(TOPDIR)/.config
-include $(TOPDIR)/..config.cmd
-include $(TOPDIR)/.depends

all : $(TOPDIR)/.depends $(configs) $(subdir-y)

./.config: $(configs)
	$(call descend,scripts/kconfig,conf)
	@if [ ! -e $@ ]; then \
		cp $(TOPDIR)/def-configs/opie $@; \
	fi;
	@$(MAKE) -C scripts/kconfig conf;
	./scripts/kconfig/conf -s ./config.in

xconfig: $(configs)
	$(call descend,scripts/kconfig,qconf)
	./scripts/kconfig/qconf ./config.in

menuconfig: $(configs) scripts/lxdialog/lxdialog
	$(call descend,scripts/kconfig,mconf)
	./scripts/kconfig/mconf ./config.in

config: $(configs)
	$(call descend,scripts/kconfig,conf)
	./scripts/kconfig/conf ./config.in
 
oldconfig: $(configs)
	$(call descend,scripts/kconfig,conf)
	./scripts/kconfig/conf -o ./config.in
 
randconfig: $(configs)
	$(call descend,scripts/kconfig,conf)
	./scripts/kconfig/conf -r ./config.in
 
allyesconfig: $(configs)
	$(call descend,scripts/kconfig,conf)
	./scripts/kconfig/conf -y ./config.in
 
allnoconfig: $(configs)
	$(call descend,scripts/kconfig,conf)
	./scripts/kconfig/conf -n ./config.in
 
defconfig: $(configs)
	$(call descend,scripts/kconfig,conf)
	./scripts/kconfig/conf -d ./config.in


include $(TOPDIR)/Rules.make

