#!/bin/sh

QTE_VERSION=2.3.2
DEB_VERSION=2.0

# Have to do this here, since CVS can't store symlinks
mkdir -p etc/rc2.d
rm -f etc/rc2.d/S98qpe
ln -s ../init.d/qpe etc/rc2.d/S98qpe

VERSION_MAJ=$(sed -n -e 's/.*QPE_VERSION "\([0-9]*\)\..*\..*".*/\1/p' <$QPEDIR/include/qpe/version.h)
VERSION_MIN=$(sed -n -e 's/.*QPE_VERSION ".*\.\([0-9]*\)\..*".*/\1/p' <$QPEDIR/include/qpe/version.h)
VERSION_PAT=$(sed -n -e 's/.*QPE_VERSION ".*\..*\.\([0-9]*\).*/\1/p' <$QPEDIR/include/qpe/version.h)
if grep -q 'QPE_VERSION .*snapshot' $QPEDIR/include/qpe/version.h
then
    VERSION_CVS="_$(date +%Y%m%d)"
else
    VERSION_CVS=""
fi

QPE_VERSION=$VERSION_MAJ.$VERSION_MIN.$VERSION_PAT

ARCH=arm
STRIP=arm-linux-strip
STRIP_FILES="*Advanced RISC Machines ARM*not stripped"

TDIR=/tmp/ipk$$
DATADIR=$TDIR/data
CTRLDIR=$TDIR/control

IMAGEDIR=
VERB=
LIST=
RPM=

while [ $# -ne 0 ]
do
    case "$1" in
     -v)
	VERB=1
	echo >&2 "Packaging for version $VERSION_MAJ.$VERSION_MIN.$VERSION_PAT$VERSION_CVS"
    ;; -l)
	LIST=1
    ;; -i)
	shift
	IMAGEDIR=$1
	DATADIR=$IMAGEDIR
	mkdir -p $IMAGEDIR
    ;; -rpm)
	if [ "$QPEDIR" != "/opt/Qtopia" ]
	then
	    echo >&2 '$QPEDIR is not the standard /usr/Qtopia directory.'
	    sleep 1
	    #exit 1
	fi
	RPM=1
    ;; -arch)
	shift
	ARCH=$1
	STRIP=
	STRIP_FILES=
    ;; /*)
	FILES="$FILES $1"
    ;; *)
	FILES="$FILES $PWD/$1"
    esac
    shift
done


if [ -z "$FILES" ]
then
    FILES=`find $QPEDIR -name "*.control" -print`
fi

RDIR=$PWD
cd $QPEDIR

for i in $FILES
do
    rm -rf $TDIR

    mkdir -p $DATADIR
    mkdir -p $CTRLDIR

    packagename=${i##*/}; packagename=${packagename%.control}
    version=$(eval echo '"'$(sed -n -e "s/^Version: *//p" $i)'"')
    depends=$(eval echo '"'$(sed -n -e "s/^Depends: *//p" $i)'"')
    files=$(eval echo $(sed -n -e "s/^Files://p" $i))
    arch=$(eval echo $(sed -n -e "s/^Arch://p" $i))
    section=$(sed -n -e "s/^Section: *//p" $i)
    license=$(sed -n -e "s/^License: *//p" $i)
    summary=$(sed -n -e "s/^Description: *//p" $i)
    package=${packagename}_${version}_$ARCH
    ERROR=
    if [ -z "$files" ]
    then
	mkdir -p $DATADIR/usr/share/doc/$packagename
    else
	for f in $files
	do
	    if [ -d $f ]
	    then
		ffiles=$(find $f -type f -o -type b -o -type c -o -type l)
	    else
		ffiles=$f
	    fi
	    for ff in $ffiles
	    do
		case $ff in
		    */CVS/*)
		    continue
		;;	*~)
		    continue
		;;	*.control)
		    continue
		;; $QTDIR/*)
		    BASE=$(dirname /usr/${ff#$QTDIR/})
		;; etc/*.d/*)
		    BASE=$(dirname /$ff)
		;; ipaq/*)
		    BASE=$(dirname ${ff#ipaq})
		;; *)
		    # For SHARP ROM compatibility. Should change to Qtopia.
		    BASE=/opt/QtPalmtop/$(dirname $ff)
		esac

		if [ -f $ff -o -b $ff -o -c $ff ]
		then
		    D=$DATADIR$BASE
		    if [ -x $ff -a -n "$STRIP" ]
		    then
			case $(file $ff) in
			 $STRIP_FILES)
			    $STRIP $ff
			 ;; *)
			esac
		    fi
		    if [ -n "$RPM" ]
		    then
			case "$ff" in
			 /*) RPMFILES="$RPMFILES $ff"
			;; *) RPMFILES="$RPMFILES $QPEDIR/$ff"
			esac
		    else
			mkdir -p $D
			if cp -a $ff $D
			then
			    true
			else
			    ERROR=1
			fi
		    fi
		else
		    echo >&2 "$0: $i: No such file: $ff"
		    ERROR=1
		fi
	    done
	done
    fi
    if [ -z "$ERROR" ]
    then
	if [ -n "$RPM" ]
	then
	    SPEC=/tmp/mkipks-rpm-$$.spec
	    echo >$SPEC "Summary: $summary"
	    echo >>$SPEC "Name: $packagename"
	    echo >>$SPEC "Group: $section" ##########
	    echo >>$SPEC "License: $license"
	    echo >>$SPEC "Version: ${version%-*}"
	    echo >>$SPEC "Release: ${version#*-}"
 
	    echo >>$SPEC "%description"
	    sed -n -e '/^Description:/,$ p' $i | tail +2 >>$SPEC
	    echo >>$SPEC "%files"
	    echo >>$SPEC "%defattr(-,root,root)"
	    /bin/ls $RPMFILES >>$SPEC
	    rpm -bb --target $ARCH-unknown-linux $SPEC
	    # rm $SPEC
	elif [ -z "$IMAGEDIR" ]
	then
	    #size=$(du -h -s $DATADIR | sed -e 's/[	 ].*//')
	    size=$(mkfs.jffs2 -r $DATADIR | wc -c)
	    echo "Package: $packagename" >$CTRLDIR/control
	    echo "Installed-Size: $size" >>$CTRLDIR/control
	    echo "Filename: ./$package.ipk" >>$CTRLDIR/control
	    echo "Version: $version" >>$CTRLDIR/control
	    echo "Depends: $depends" >>$CTRLDIR/control
	    egrep -v "^(Files|Version|Depends):" >>$CTRLDIR/control $i
	    echo "$DEB_VERSION" >$TDIR/debian-binary
	    base=${i%.control}
	    scripts="preinst postinst prerm postrm"
	    for pf in $scripts
	    do
		if [ -x ${base}.$pf ]
		then
		    cp ${base}.$pf $CTRLDIR/$pf
		fi
	    done
	    if [ "$UID" = 0 ]
	    then
		chown -R root.root $TDIR
	    fi
	    ( cd $CTRLDIR; tar cfz ../control.tar.gz ./*; )
	    ( cd $DATADIR; tar cfz ../data.tar.gz ./*; )
	    ( cd $TDIR; rm -rf control data; tar cf - ./debian-binary ./control.tar.gz ./data.tar.gz; ) | gzip >$RDIR/$package.ipk
	    RESULT=$package.ipk
	    if [ -n "$VERB" ]
	    then
		echo >&2 "Built $RESULT ($size)"
	    fi
	    if [ -n "$LIST" ]
	    then
		echo $RESULT
	    fi
	fi
    else
	echo >&2 "Not building $package package"
    fi
done
