TEMPLATE	= app
#CONFIG		= qt warn_on debug
CONFIG		= qt warn_on release
HEADERS		= usermanager.h userdialog.h groupdialog.h passwd.h
SOURCES		= usermanager.cpp userdialog.cpp groupdialog.cpp passwd.h main.cpp
INCLUDEPATH	+= $(OPIEDIR)/include
DEPENDPATH	+= $(OPIEDIR)/include
LIBS            += -lqpe -lcrypt
TARGET		= usermanager
DESTDIR         = $(OPIEDIR)/bin
