TEMPLATE	= app
CONFIG		= qt warn_on release
#DESTDIR		= $(OPIEDIR)/bin
HEADERS		=
SOURCES		= testxmltodo.cpp
INTERFACES	= 
INCLUDEPATH	+= $(OPIEDIR)/include
DEPENDPATH	+= $(OPIEDIR)/include
LIBS            += -lqpe -lopie-two
TARGET		= testxmltodo
