TEMPLATE        = lib
#CONFIG          += qt warn_on release
CONFIG		+= qt warn_on debug
#DESTDIR         = $(OPIEDIR)/plugins/networksetup
HEADERS		= wlanimp.h wlanmodule.h wextensions.h
SOURCES		= wlanimp.cpp wlanmodule.cpp wextensions.cpp
INCLUDEPATH	+= $(OPIEDIR)/include ../
DEPENDPATH	+= $(OPIEDIR)/include
LIBS            += -lqpe
INTERFACES	= wlan.ui info.ui
TARGET		= wlanplugin
VERSION		= 1.0.0
