#!/bin/sh
# Starts opiealarm, which only runs while the iPaq sleeps 
# and wakes it up when the RTC alarm goes off.

start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/opiealarm.pid --exec /opt/QtPalmtop/bin/opiealarm
