#!/bin/sh

#
# This is needed to ensure the single build will work
# The names of the header files clash with names of other headers in Qt/Palmtop
#


for file in *.c
do

    echo "fixing $file"
    sed "s/global.h/libmad_global.h/" $file > $file.tmp
    sed "s/version.h/libmad_version.h/" $file.tmp > $file
    sed "s/config.h/libmad_config.h/" $file > $file.tmp
    mv $file.tmp $file

done


mv global.h libmad_global.h
mv version.h libmad_version.h
mv config.h libmad_config.h


