#!/bin/sh

# small shell script to generate our API docs
# it'll copy over qt

#
# create directory structure
echo "Creating directory structure"
rm -rf $OPIEDIR/apidocs
mkdir $OPIEDIR/apidocs
mkdir $OPIEDIR/apidocs/api
mkdir $OPIEDIR/apidocs/common
mkdir $OPIEDIR/apidocs/qt
mkdir $OPIEDIR/apidocs/libqpe
mkdir $OPIEDIR/apidocs/libopie
mkdir $OPIEDIR/apidocs/pim

# now copy qt doc
echo "Scanning and copying QT docu"
cp -R $QTDIR/doc/html/* $OPIEDIR/apidocs/qt
doxytag -t $OPIEDIR/apidocs/qt/qt.tag $OPIEDIR/apidocs/qt

cp -r $OPIEDIR/doc/common/* $OPIEDIR/apidocs/common
# now start with libqpe
echo "Creating docu for qpe"
cp $OPIEDIR/doc/Doxyfile_libqpe $OPIEDIR/library/Doxyfile
cd $OPIEDIR/library
doxygen Doxyfile
rm -f Doxyfile

# now do libopie
echo "Creating docu for libopie"
cp $OPIEDIR/doc/Doxyfile_libopie $OPIEDIR/libopie/Doxyfile
cd $OPIEDIR/libopie
doxygen Doxyfile
rm -f Doxyfile

echo "Creating docu for PIM"
# now it's time for libopie/pim
cp $OPIEDIR/doc/Doxyfile_pim $OPIEDIR/libopie/pim/Doxyfile
cd $OPIEDIR/libopie/pim
doxygen Doxyfile
rm -f Doxyfile

echo "Making mainpage"
# now generate the mainpage
cp $OPIEDIR/doc/Doxyfile_main $OPIEDIR/Doxyfile
cp $OPIEDIR/doc/Mainpage.dox $OPIEDIR/
cd $OPIEDIR
doxygen Doxyfile
rm -f Doxyfile
rm -f Mainpage.dox

echo "Done with generation!!! hopefully grin"
