#!/bin/sh
# 

export LOGNAME=root
export HOME=/$LOGNAME
export QWS_DISPLAY=Transformed:Rot270:0
export QTDIR=/opt/QtPalmtop
export OPIEDIR=/opt/QtPalmtop
export QPEDIR=/opt/QtPalmtop
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPIEDIR/lib
export PATH=$PATH:$OPIEDIR/bin

#this sets the iPaqs powerbutton to mapable
echo 1 > /proc/sys/ts/suspend_button_mode

if [ ! -x $OPIEDIR/bin/qpe ] ; then exit 0 ; fi

$OPIEDIR/bin/qpe-reorgfiles

. /etc/profile

killproc() {
        pid=`/bin/ps -e | /bin/sed -n -e '/\<'$1'\>/ s/^ *\([0-9][0-9]*\).*/\1/p'`
        [ "$pid" != "" ] && kill $pid
}

case $1 in
'start')
	echo "Starting QPE..."

	cd $HOME

	rm -f /etc/rc2.d/S99x # Can't have both running!

	$OPIEDIR/bin/qpe 2>/dev/null >/dev/null &

	;;
'stop')
        echo "Killing QPE..."
        killproc qpe
        ;;
*)
        echo "usage: $0 { start | stop }"
        ;;
esac

