all:
	cp *.sh ../../../../bin/
clean:
	rm ../../../../bin/diskfree.sh
	rm ../../../../bin/filesystem_mounter.sh
	rm ../../../../bin/hostlist.sh
	rm ../../../../bin/killproc.sh
	rm ../../../../bin/launcher_refresh.sh
	rm ../../../../bin/logviewer.sh
	rm ../../../../bin/opie-sh-wavelanchooser.sh
	rm ../../../../bin/rsyncme.sh
	rm ../../../../bin/service_manager.sh
	rm ../../../../bin/usbnetctrl.sh
	rm ../../../../bin/stowctrl.sh
