#!/bin/sh

permout ()
{
	if [ -e $1 ]
	then
		chown root $1
	else
		echo Warning: $1 does not exist.
		return 1
	fi
}

if [ -e /proc/hal/model ]; then
	devs=/dev/sound/dsp /dev/sound/mixer /dev/touchscreen/* \
		/dev/fb/0 /dev/vc/0
else
	devs=/dev/dsp /dev/dsp1 /dev/mixer /dev/ts /dev/fb0 \
		/dev/sharp* /dev/collie*
fi

for i in $devs; do
	permout $i
done
