#!/bin/sh

USER=$1

if [ -e /proc/hal/model ]; then

  # fix for misconfigured devfsd
  chmod +x /dev/sound /dev/touchscreen /dev/fb /dev/vc

  [ -e /dev/sound/dsp ]     && chown $USER /dev/sound/dsp
  [ -e /dev/sound/mixer ]   && chown $USER /dev/sound/mixer
  [ -e /dev/touchscreen/0 ] && chown $USER /dev/touchscreen/0
  [ -e /dev/fb/0 ]          && chown $USER /dev/fb/0
  [ -e /dev/vc/0 ]          && chown $USER /dev/vc/0
fi

