/*
 * This file has been generated by doing
 * find . -name "*"|xargs grep -h '#define UDP_PORT' > udp_ports.h
 * in the root directory of Ethereal 0.9.15. Cudos to the Ethereal Team.
 * -- Michael 'Mickey' Lauer <mickeyl@handhelds.org>
 */

#define UDP_PORT_AODV	654
#define UDP_PORT_LENGTH     2
#define UDP_PORT_OFFSET     PARAMETER_VALUE_OFFSET
#define UDP_PORT_RAS1 1718
#define UDP_PORT_RAS2 1719
#define UDP_PORT_CPHA	8116
#define UDP_PORT_DDTP	1052
#define UDP_PORT_CUPS	631
#define UDP_PORT_DLSW		2067
#define UDP_PORT_ISAKMP	500
#define UDP_PORT_L2TP   1701
#define UDP_PORT_IAPP     2313
#define UDP_PORT_HSRP   1985
#define UDP_PORT_SSDP			1900
#define UDP_PORT_TACACS	49
#define UDP_PORT_CLDAP			389
#define UDP_PORT_VINES	573
#define UDP_PORT_NBNS	137
#define UDP_PORT_NBDGM	138
#define UDP_PORT_XYPLEX    173
#define UDP_PORT_PIM_RP_DISC 496
#define UDP_PORT_SLIMP3_V1    1069
#define UDP_PORT_SLIMP3_V2    3483
#define UDP_PORT_RMCP		623
#define UDP_PORT_RMCP_SECURE	664
#define UDP_PORT_SYSLOG 514
#define UDP_PORT_SNMP		161
#define UDP_PORT_SNMP_TRAP	162
#define UDP_PORT_TFTP    69
#define UDP_PORT_TIME    37
#define UDP_PORT_STUN 	3478
#define UDP_PORT_SRVLOC	427
#define UDP_PORT_TZSP	0x9090
#define UDP_PORT_WCCP	2048
#define UDP_PORT_MSPROXY 1745
#define UDP_PORT_BOOTPS  67
#define UDP_PORT_BOOTPC  68
#define UDP_PORT_XDMCP 177
#define UDP_PORT_DHCPV6_DOWNSTREAM	546
#define UDP_PORT_DHCPV6_UPSTREAM	547
#define UDP_PORT_DNS     53
#define UDP_PORT_MDNS    5353
#define UDP_PORT_ICP    3130
#define UDP_PORT_ICQ	4000
#define UDP_PORT_IPX    213		/* RFC 1234 */
#define UDP_PORT_LDP 646
#define UDP_PORT_LLC1   12000
#define UDP_PORT_LLC2   12001
#define UDP_PORT_LLC3   12002
#define UDP_PORT_LLC4   12003
#define UDP_PORT_LLC5   12004
#define UDP_PORT_MIP    434
#define UDP_PORT_NCP		524
#define UDP_PORT_NTP	123
#define UDP_PORT_RIP    520
#define UDP_PORT_SAP	9875
#define UDP_PORT_SIP 5060
#define UDP_PORT_TIMED	525
#define UDP_PORT_RIPNG  521
#define UDP_PORT_WSP			9200		/* wap-wsp			*/
#define UDP_PORT_WTP_WSP		9201		/* wap-wsp-wtp		*/
#define UDP_PORT_WTLS_WSP		9202		/* wap-wsp-s		*/
#define UDP_PORT_WTLS_WTP_WSP		9203		/* wap-wsp-wtp-s	*/
#define UDP_PORT_WSP_PUSH		2948		/* wap-wsp		*/
#define UDP_PORT_WTLS_WSP_PUSH		2949		/* wap-wsp-s		*/
#define UDP_PORT_WHO    513
#define UDP_PORT_KERBEROS		88
#define UDP_PORT_SFLOW 6343
#define UDP_PORT_LAPLINK 1547
#define UDP_PORT_NETFLOW	2055
#define UDP_PORT_RX_LOW		7000
#define UDP_PORT_RX_HIGH	7009
#define UDP_PORT_RX_AFS_BACKUPS	7021
#define UDP_PORT_MGCP_GATEWAY 2427
#define UDP_PORT_MGCP_CALLAGENT 2727
#define UDP_PORT_PCLI 9000
#define UDP_PORT_ARTNET 0x1936
#define UDP_PORT_TERREDO 3544
#define UDP_PORT_RADIUS		1645
#define UDP_PORT_RADIUS_NEW	1812
#define UDP_PORT_RADACCT	1646
#define UDP_PORT_RADACCT_NEW	1813
