TEMPLATE	= app
DESTDIR         = .
#CONFIG		= qt warn_on debug
CONFIG		= qt warn_on release
HEADERS		= frame.h lib.h
SOURCES		= nullvideo.o frame.cpp lib.cpp mainTest.cpp 
INCLUDEPATH	+= $(OPIEDIR)/include /usr/include
DEPENDPATH	+= $(OPIEDIR)/include /usr/include
LIBS            += -lxine -lxineutils
TARGET          = zeckeplayer