#!/usr/bin/perl

use File::Basename;

die "need a filename!" if (!length($ARGV[0]));

$cvsversion= dirname($0) . "/cvsversion";
$version=`$cvsversion $ARGV[0]`;

chop $version;
my $vold = $version;
my $vnew = $version;

if ($version=~/^(.*)\.1$/) {
  $vold = $1 if ($version=~/^([^.]\.[^.])\.[^.]\.[^.]$/);
}
else {
  if ($version=~/^(.*)\.([^.]*)$/) { $v1 = $1; $v2 = $2 } 
  $v2old = ${v2}-1;
  $vold = $v1 . '.' . $v2old;
}
print "cvs -f log -N -r$vnew $ARGV[0]\n";
system("cvs -f log -N -r$vnew $ARGV[0]");
print "cvs -f diff -bp -u -r$vold -r$vnew $ARGV[0]\n";
system("cvs -f diff -bp -u -r$vold -r$vnew $ARGV[0]");
