#!/bin/sh
# (C) 2001 Charles Samuels <charles@kde.org>
#
# This script reverts all the files given on the command
# by one version, then you can commit them.  This
# is like a less polite version of cvsblame ;)
#

for i in $@ ;
do

    text=`cvs log "$i" | grep 'revision[^s]'`
    current=`echo $text | awk '{print $2}'`
    previous=`echo $text | awk '{print $4}'`
    echo $i... "(reverting from $current to $previous)"
    cvs up -j $current -j $previous $i
done

