#!/bin/sh
#
# Adds a file to which ever repository is appropriate
#
# Copyright 1999-2000 Trolltech AS.  All rights reserved.
#


if [ $P4PORT = "lupinella:866" ]
then
    p4 edit $@
else
    echo Need to put some kind of cvs command here in q_cvs_edit !!
    # cvs edit $@
fi


