TEMPLATE	= lib
CONFIG		+= qt warn_on release
HEADERS	=   clipboard.h clipboardappletimpl.h
SOURCES	=   clipboard.cpp clipboardappletimpl.cpp
TARGET		= clipboardapplet
DESTDIR		= ../../plugins/applets
INCLUDEPATH += $(QPEDIR)/include
DEPENDPATH      += ../$(QPEDIR)/include
LIBS            += -lqpe
VERSION		= 1.0.0
