TEMPLATE	= app
#CONFIG		= qt warn_on debug
CONFIG		= qt warn_on release
HEADERS		= today.h TodoItem.h minidom.h todaybase.h todayconfig.h
SOURCES		= main.cpp today.cpp todaybase.cpp todayconfig.cpp minidom.c TodoItem.cpp
INCLUDEPATH	+= $(OPIEDIR)/include
DEPENDPATH	+= $(OPIEDIR)/include
LIBS            += -lqpe
INTERFACES	= 
TARGET		= today
DESTDIR		= $(OPIEDIR)/bin
