<!DOCTYPE TS><TS>
<defaultcodec>iso8859-1</defaultcodec>
<context>
    <name>HelpWindow</name>
    <message>
        <source>Help for SFCave</source>
        <translation>Hilfe für SFCave</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>&lt;qt&gt;&lt;h1&gt;SFCave Help&lt;/h1&gt;&lt;p&gt; SFCave is a flying game for the Zaurus.&lt;br&gt;&lt;br&gt; The aim is to stay alive for as long as possible and get the highest score you can.&lt;br&gt;&lt;br&gt;There are three game types currently - SFCave, Gates, and Fly.&lt;br&gt;&lt;b&gt;SFCave&lt;/b&gt; is a remake of the classic SFCave game - fly through the cavern avoiding all the blocks that just happen to be hanging in midair&lt;br&gt;&lt;br&gt;&lt;b&gt;Gates&lt;/b&gt; is similar to SFCave but instead you must fly through the without crashing.&lt;br&gt;&lt;br&gt;&lt;b&gt;Fly&lt;/b&gt; is somewhat different to SFCave and above. Instead, you have are flying in the open air above a scrolling landscape, and the aim is to hug the ground - the closer to the land you fly the more points scored.&lt;br&gt;&lt;br&gt;&lt;br&gt;Basic instruction - Press &lt;b&gt;Up&lt;/B&gt; or &lt;b&gt;Down&lt;/b&gt; on the circle pad to start a new game, press the middle of the pad to apply thrust (makes you go up), and release the pad to remove thrust and drop down.&lt;br&gt;&lt;br&gt;Also, if playing the Fly game, you can press z to toggle the display of the scoring zones. This will display 4 red lines at varying heights above the landscape - if your ship falls into this zone, point are scored. The closer to the landscape you get the more points you get.&lt;br&gt;&lt;br&gt;In addition, SFCave has replays - save and load too so you can show off to all your friends (or vice versa). Currently, this is in its infancy but will improve.&lt;br&gt;To use, once you have crashed, press &apos;r&apos; to replay the last game.&lt;br&gt;To save the replay press &apos;s&apos;.&lt;br&gt;To load a saved replay press &apos;l&apos; (after you&apos;ve crashed at least once).&lt;br&gt;&lt;br&gt;Replays are currently saved to your home directory in a file called sfcave.replay.This file can be copied and given to others as long as it it put in their home directory.&lt;br&gt;&lt;br&gt;Have lots of fun.&lt;br&gt;Andy&lt;/p&gt;&lt;/qt&gt;</source>
        <translation>&lt;qt&gt;&lt;h1&gt;SFCave Hilfe&lt;/h1&gt;&lt;p&gt;SFCave ist ein Flugspiel für den Zaurus.&lt;br&gt;&lt;br&gt;Das Ziel ist es so lange wie möglich am leben zu bleiben um einen möglichst hohen Punktestand zu bekommen.&lt;br&gt;&lt;br&gt;Zur Zeit gibt es drei verschiedene Spielarten: SFCave, Gates und Fly.&lt;br&gt;&lt;b&gt;SFCave&lt;/b&gt; ist ein Remake von dem klassischen SFCave Spiel: Man fliegt durch eine Höhle bei Vermeidung aller im Weg befindlichen Hindernisse.&lt;br&gt;&lt;br&gt;&lt;b&gt;Gates&lt;/b&gt; ist SFCave ähnlich, allerdings muss man durch Tore fliegen ohne den Boden zu berühren&lt;br&gt;&lt;br&gt;&lt;b&gt;Fly&lt;/b&gt; ist etwas anders als SFCave. Hier ist es das Ziel möglichst nahe am Boden zu fliegen. Je näher am Boden man fliegt ohne ihn zu berühren, desto mehr Punkte gibt es.&lt;br&gt;&lt;br&gt;Anleitung: Drücke hoch oder runter auf dem Steuerkreuz um ein neues Spiel zu starten, der mittlere Knopf lässt den Flieger steigen. Im Fly Spiel kann man mit der z-Taste den Punktelevel anzeigen. Innerhalb der roten Linien gibt es Punkte. SFCaves kann ein Spiel wiederholen (Replay). Nachdem das Spiel beendet ist kann man es sich durch Drücken von &apos;r&apos; nochmal anzeigen lassen. Ein Replay kann durch drücken von &apos;s&apos; gespeichert werden. Um ein gespeichertes Replay zu laden einfach &apos;l&apos; drücken nach einem Absturz.&lt;br&gt;&lt;br&gt;Viel Spass!&lt;br&gt;Andy&lt;/p&gt;&lt;/qt&gt;</translation>
    </message>
</context>
</TS>
